#!/usr/bin/env python3
# fix_07_purchasing_final.py — patches based on ACTUAL file content from diag output
import os, sys, shutil, re
from datetime import datetime

BASE     = "/home/momar/Projects/POS_DEV/posv1_dev10"
BACKEND  = BASE + "/pos_backend/inventory"
FRONTEND = BASE + "/pos_frontend/src"
STAMP    = datetime.now().strftime("%Y%m%d_%H%M%S")

# ── Helpers ────────────────────────────────────────────────
def abort(msg):
    print("ABORT: " + msg); sys.exit(1)

def backup(path):
    bak = path + ".bak_" + STAMP
    shutil.copy2(path, bak)
    print("  backup -> " + bak)

def read(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()

def write(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def apply_fix(label, path, old, new):
    if not os.path.exists(path):
        abort(path + " not found")
    src = read(path)
    if old not in src:
        print("  SKIP (pattern not found): " + label)
        return False
    backup(path)
    write(path, src.replace(old, new, 1))
    print("  OK: " + label)
    return True

def update_changelog(entry):
    if not os.path.exists(BASE + "/pos_backend/CHANGELOG.md"):
        return
    src = read(BASE + "/pos_backend/CHANGELOG.md")
    if entry[:30] in src:
        return
    write(BASE + "/pos_backend/CHANGELOG.md", entry + "\n" + src)

# ── Section 1: models.py — ازالة check_and_auto_resolve المكررة ───────────────
def fix_models():
    path = BACKEND + "/models.py"
    print("\n[models.py]")

    # ازالة النسخة الاولى المكررة (الغلط) وابقاء التانية الصح
    old = (
        "    def check_and_auto_resolve(self):\n"
        "        \"\"\"يحل التنبيه اوتوماتيك لو كل POs مرتبطة استُلمت\"\"\"\n"
        "        pos = self.linked_pos.all()\n"
        "        if pos.exists() and not pos.exclude(status='received').exists():\n"
        "            self.resolve()\n"
        "\n"
        "    # Fix-4: يحل التنبيه تلقائياً لو كل الـ POs المرتبطة استُلمت\n"
        "    def check_and_auto_resolve(self):\n"
        "        pos = self.linked_pos.all()\n"
        "        if pos.exists() and all(po.status == 'received' for po in pos):\n"
        "            self.resolve()\n"
        "            return True"
    )
    new = (
        "    # Fix-4: يحل التنبيه تلقائياً لو كل الـ POs المرتبطة استُلمت\n"
        "    def check_and_auto_resolve(self):\n"
        "        pos = self.linked_pos.all()\n"
        "        if pos.exists() and all(po.status == 'received' for po in pos):\n"
        "            self.resolve()\n"
        "            return True"
    )
    apply_fix("models.py: remove duplicate check_and_auto_resolve", path, old, new)

    # ازالة created_by المكررة (الاولى بعد assigned_to مباشرة)
    old = (
        "        on_delete=models.SET_NULL, related_name='assigned_alerts'\n"
        "    )\n"
        "    # Fix-7: اليوزر اللي انشا التنبيه\n"
        "    created_by    = models.ForeignKey(\n"
        "        settings.AUTH_USER_MODEL, null=True, blank=True,\n"
        "        on_delete=models.SET_NULL, related_name='created_alerts'\n"
        "    )\n"
        "    # Fix-2: ManyToMany بدل FK — لدعم اكتر من PO لكل تنبيه\n"
        "    linked_pos    = models.ManyToManyField(\n"
        "        PurchaseOrder, blank=True,\n"
        "        related_name='linked_alerts',\n"
        "        verbose_name='اوامر الشراء المرتبطة'\n"
        "    )\n"
        "    created_by    = models.ForeignKey(\n"
        "        settings.AUTH_USER_MODEL, null=True, blank=True,\n"
        "        on_delete=models.SET_NULL, related_name='created_alerts'\n"
        "    )"
    )
    new = (
        "        on_delete=models.SET_NULL, related_name='assigned_alerts'\n"
        "    )\n"
        "    # Fix-7: اليوزر اللي انشا التنبيه\n"
        "    created_by    = models.ForeignKey(\n"
        "        settings.AUTH_USER_MODEL, null=True, blank=True,\n"
        "        on_delete=models.SET_NULL, related_name='created_alerts'\n"
        "    )\n"
        "    # Fix-2: ManyToMany بدل FK — لدعم اكتر من PO لكل تنبيه\n"
        "    linked_pos    = models.ManyToManyField(\n"
        "        PurchaseOrder, blank=True,\n"
        "        related_name='linked_alerts',\n"
        "        verbose_name='اوامر الشراء المرتبطة'\n"
        "    )"
    )
    apply_fix("models.py: remove duplicate created_by field", path, old, new)

# ── Section 2: api.js — اضافة assign endpoints ────────────────────────────────
def fix_api_js():
    path = FRONTEND + "/services/api.js"
    print("\n[api.js]")

    # الـ pattern الفعلي من الـ diag (spacing مختلف)
    old = (
        "  resolveAlert:          (id, data={}) => api.post(`/inventory/alerts/${id}/resolve/`, data),\n"
        "  addAlertNote:          (id, data)     => api.post(`/inventory/alerts/${id}/add_note/`, data),\n"
        "  createPoFromAlert:     (id, data)     => api.post(`/inventory/alerts/${id}/create_purchase_order/`, data),\n"
        "  updateAlertMeta:       (id, data)     => api.patch(`/inventory/alerts/${id}/update_meta/`, data),"
    )
    new = (
        "  resolveAlert:          (id, data={}) => api.post(`/inventory/alerts/${id}/resolve/`, data),\n"
        "  addAlertNote:          (id, data)     => api.post(`/inventory/alerts/${id}/add_note/`, data),\n"
        "  createPoFromAlert:     (id, data)     => api.post(`/inventory/alerts/${id}/create_purchase_order/`, data),\n"
        "  updateAlertMeta:       (id, data)     => api.patch(`/inventory/alerts/${id}/update_meta/`, data),\n"
        "  assignAlertToMe:       (id)           => api.post(`/inventory/alerts/${id}/assign_to_me/`),\n"
        "  assignAlertToUser:     (id, data)     => api.post(`/inventory/alerts/${id}/assign_to_user/`, data),\n"
        "  unassignAlert:         (id)           => api.post(`/inventory/alerts/${id}/unassign/`),"
    )
    apply_fix("api.js: add assign endpoints", path, old, new)

# ── Section 3: PurchasingPage.jsx — كتابة الملف من الصفر ─────────────────────
def fix_purchasing_page():
    path = FRONTEND + "/pages/PurchasingPage.jsx"
    print("\n[PurchasingPage.jsx]")

    src = read(path)
    print("  current size: " + str(len(src)) + " chars")

    # الملف الحالي فاضي أو مختلف تماماً — هنكتبه من الصفر
    # لكن أول بكره ناخد backup
    backup(path)

    content = (
        "import React, { useCallback, useEffect, useState } from 'react';\n"
        "import { inventoryAPI, productsAPI } from '../services/api';\n"
        "import { useAuth } from '../context/AuthContext';\n"
        "\n"
        "const fmt = (n) => Number(n || 0).toFixed(2);\n"
        "\n"
        "const Badge = ({ label, color }) => {\n"
        "  const map = {\n"
        "    green:  'bg-green-100 text-green-800',\n"
        "    red:    'bg-red-100 text-red-800',\n"
        "    yellow: 'bg-yellow-100 text-yellow-800',\n"
        "    blue:   'bg-blue-100 text-blue-800',\n"
        "    gray:   'bg-gray-100 text-gray-600',\n"
        "    purple: 'bg-purple-100 text-purple-800',\n"
        "  };\n"
        "  return <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${map[color]||map.gray}`}>{label}</span>;\n"
        "};\n"
        "\n"
        "const statusColor = (s) => ({ draft:'gray', ordered:'blue', received:'green', cancelled:'red' }[s]||'gray');\n"
        "const Spinner = () => (\n"
        "  <div className=\"flex items-center justify-center h-40\">\n"
        "    <i className=\"fas fa-spinner fa-spin text-4xl text-blue-500\"></i>\n"
        "  </div>\n"
        ");\n"
        "const Toast = ({ msg, type }) => (\n"
        "  <div className={`fixed top-5 left-1/2 -translate-x-1/2 z-50 px-5 py-3 rounded-2xl shadow-xl font-bold text-sm\n"
        "    ${type===\"error\"?\"bg-red-600 text-white\":\"bg-green-600 text-white\"}`}>{msg}</div>\n"
        ");\n"
        "const Modal = ({ title, onClose, children }) => (\n"
        "  <div className=\"fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4\" onClick={onClose}>\n"
        "    <div className=\"bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto\"\n"
        "      onClick={(e)=>e.stopPropagation()}>\n"
        "      <div className=\"flex justify-between items-center px-5 py-4 border-b\">\n"
        "        <h3 className=\"font-black text-gray-800\">{title}</h3>\n"
        "        <button onClick={onClose} className=\"text-gray-400 hover:text-gray-700 font-black text-xl\">\u00d7</button>\n"
        "      </div>\n"
        "      <div className=\"p-5\">{children}</div>\n"
        "    </div>\n"
        "  </div>\n"
        ");\n"
        "const Field = ({ label, children }) => (\n"
        "  <div>\n"
        "    <label className=\"block text-xs font-bold text-gray-500 mb-1\">{label}</label>\n"
        "    {children}\n"
        "  </div>\n"
        ");\n"
        "const INP = 'w-full border border-gray-200 rounded-xl px-3 py-2 text-sm outline-none"
        " focus:border-blue-500 focus:ring-2 focus:ring-blue-100 bg-white transition';\n"
        "\n"
        "// ── Priority / Status configs ──────────────────────────────────\n"
        "const priorityConfig = {\n"
        "  low:      { label: '\u0645\u0646\u062e\u0641\u0636\u0629',  color: 'bg-gray-100  text-gray-600',    dot: 'bg-gray-400'   },\n"
        "  medium:   { label: '\u0645\u062a\u0648\u0633\u0637\u0629',  color: 'bg-blue-100  text-blue-700',    dot: 'bg-blue-500'   },\n"
        "  high:     { label: '\u0639\u0627\u0644\u064a\u0629',   color: 'bg-orange-100 text-orange-700', dot: 'bg-orange-500' },\n"
        "  critical: { label: '\u062d\u0631\u062c\u0629',    color: 'bg-red-100   text-red-700',     dot: 'bg-red-500'    },\n"
        "};\n"
        "const ticketStatusConfig = {\n"
        "  open:        { label: '\u0645\u0641\u062a\u0648\u062d\u0629',        color: 'bg-red-100    text-red-700'    },\n"
        "  in_progress: { label: '\u0642\u064a\u062f \u0627\u0644\u0645\u0639\u0627\u0644\u062c\u0629', color: 'bg-yellow-100 text-yellow-700' },\n"
        "  ordered:     { label: '\u062a\u0645 \u0627\u0644\u0637\u0644\u0628',      color: 'bg-blue-100   text-blue-700'   },\n"
        "  resolved:    { label: '\u0645\u062d\u0644\u0648\u0644\u0629',        color: 'bg-green-100  text-green-700'  },\n"
        "};\n"
        "const noteTypeConfig = {\n"
        "  note:   { label: '\u0645\u0644\u0627\u062d\u0638\u0629',      icon: '\\uD83D\\uDCDD', color: 'border-gray-200   bg-gray-50'   },\n"
        "  quote:  { label: '\u0639\u0631\u0636 \u0633\u0639\u0631',    icon: '\\uD83D\\uDCB0', color: 'border-green-200  bg-green-50'  },\n"
        "  action: { label: '\u0625\u062c\u0631\u0627\u0621',       icon: '\\u26A1',       color: 'border-blue-200   bg-blue-50'   },\n"
        "  delay:  { label: '\u0633\u0628\u0628 \u062a\u0623\u062e\u064a\u0631',  icon: '\\u23F0',       color: 'border-orange-200 bg-orange-50' },\n"
        "  system: { label: '\u062a\u062d\u062f\u064a\u062b \u0646\u0638\u0627\u0645', icon: '\\uD83D\\uDD27', color: 'border-purple-200 bg-purple-50' },\n"
        "};\n"
        "\n"
        "// ── Main Page ──────────────────────────────────────────────────\n"
        "export default function PurchasingPage() {\n"
        "  const [tab, setTab] = useState('alerts');\n"
        "  const tabs = [\n"
        "    { key: 'alerts',    label: '\u0627\u0644\u062a\u0646\u0628\u064a\u0647\u0627\u062a' },\n"
        "    { key: 'orders',    label: '\u0623\u0648\u0627\u0645\u0631 \u0627\u0644\u0634\u0631\u0627\u0621' },\n"
        "    { key: 'suppliers', label: '\u0627\u0644\u0645\u0648\u0631\u062f\u0648\u0646' },\n"
        "  ];\n"
        "  return (\n"
        "    <div dir=\"rtl\" className=\"p-4 min-h-screen bg-gray-50\">\n"
        "      <div className=\"mb-5\">\n"
        "        <h1 className=\"text-2xl font-black text-gray-800\">\u0627\u0644\u0645\u0634\u062a\u0631\u064a\u0627\u062a</h1>\n"
        "        <p className=\"text-gray-500 text-sm mt-1\">\u062a\u0646\u0628\u064a\u0647\u0627\u062a \u0627\u0644\u0645\u062e\u0632\u0648\u0646 \u00b7 \u0623\u0648\u0627\u0645\u0631 \u0627\u0644\u0634\u0631\u0627\u0621 \u00b7 \u0627\u0644\u0645\u0648\u0631\u062f\u0648\u0646</p>\n"
        "      </div>\n"
        "      <div className=\"flex gap-2 flex-wrap mb-5\">\n"
        "        {tabs.map((t) => (\n"
        "          <button key={t.key} onClick={() => setTab(t.key)}\n"
        "            className={`px-4 py-2 rounded-xl font-bold text-sm transition-all ${\n"
        "              tab === t.key ? 'bg-blue-600 text-white shadow' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'\n"
        "            }`}>{t.label}</button>\n"
        "        ))}\n"
        "      </div>\n"
        "      {tab === 'alerts'    && <AlertsPanel />}\n"
        "      {tab === 'orders'    && <PurchaseOrdersPanel />}\n"
        "      {tab === 'suppliers' && <SuppliersPanel />}\n"
        "    </div>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── AlertCard ──────────────────────────────────────────────────\n"
        "function AlertCard({ alert, onOpen }) {\n"
        "  const pr = priorityConfig[alert.priority] || priorityConfig.medium;\n"
        "  const st = ticketStatusConfig[alert.ticket_status] || ticketStatusConfig.open;\n"
        "  const isOverdue = alert.deadline && !alert.is_resolved && new Date(alert.deadline) < new Date();\n"
        "  return (\n"
        "    <div onClick={() => onOpen(alert)}\n"
        "      className={`bg-white rounded-2xl border shadow-sm p-4 cursor-pointer hover:shadow-md transition-all\n"
        "        ${alert.is_resolved ? 'opacity-60' : ''}\n"
        "        ${isOverdue ? 'border-red-400 ring-1 ring-red-300' : 'border-gray-200'}`}>\n"
        "      <div className=\"flex items-start justify-between gap-2 mb-3\">\n"
        "        <div className=\"flex-1 min-w-0\">\n"
        "          <div className=\"flex items-center gap-2 mb-1\">\n"
        "            <span className={`w-2 h-2 rounded-full flex-shrink-0 ${pr.dot}`}></span>\n"
        "            <span className=\"font-black text-gray-800 text-sm truncate\">{alert.product_name}</span>\n"
        "          </div>\n"
        "          <div className=\"flex flex-wrap gap-1.5\">\n"
        "            <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${st.color}`}>{st.label}</span>\n"
        "            <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${pr.color}`}>{pr.label}</span>\n"
        "            <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${\n"
        "              alert.alert_type==='out'?'bg-red-100 text-red-700':'bg-yellow-100 text-yellow-700'}` }>\n"
        "              {alert.alert_type==='out'?'\u0646\u0641\u0627\u062f':'\u0645\u0646\u062e\u0641\u0636'}\n"
        "            </span>\n"
        "          </div>\n"
        "        </div>\n"
        "        <div className=\"text-center flex-shrink-0\">\n"
        "          <div className={`text-2xl font-black ${alert.product_current_stock===0?'text-red-600':'text-orange-500'}`}>\n"
        "            {alert.product_current_stock ?? alert.current_stock}\n"
        "          </div>\n"
        "          <div className=\"text-xs text-gray-400\">\u0648\u062d\u062f\u0629</div>\n"
        "        </div>\n"
        "      </div>\n"
        "      <div className=\"flex items-center justify-between text-xs text-gray-500\">\n"
        "        <div className=\"flex items-center gap-3\">\n"
        "          {alert.notes_count > 0 && <span>{alert.notes_count} \u0645\u0644\u0627\u062d\u0638\u0629</span>}\n"
        "          {alert.linked_pos_count > 0 && (\n"
        "            <span className=\"text-blue-600\">{alert.linked_pos_count} \u0639\u0631\u0648\u0636 \u0634\u0631\u0627\u0621</span>\n"
        "          )}\n"
        "          {alert.assigned_to_name\n"
        "            ? <span className=\"text-green-600\">\u0645\u062e\u0635\u0635: {alert.assigned_to_name}</span>\n"
        "            : <span className=\"text-gray-400\">\u063a\u064a\u0631 \u0645\u062e\u0635\u0635</span>\n"
        "          }\n"
        "          {isOverdue && <span className=\"text-red-600 font-bold\">\u0645\u062a\u0623\u062e\u0631</span>}\n"
        "        </div>\n"
        "        <div className=\"text-left\">\n"
        "          {alert.created_by_name && <div>\u0628\u0648\u0627\u0633\u0637\u0629: {alert.created_by_name}</div>}\n"
        "          <div>{alert.created_at?.split('T')[0]}</div>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── AssignSection ──────────────────────────────────────────────\n"
        "function AssignSection({ data, onUpdated, notify }) {\n"
        "  const { user } = useAuth();\n"
        "  const [users, setUsers]       = useState([]);\n"
        "  const [selUser, setSelUser]   = useState('');\n"
        "  const [saving, setSaving]     = useState(false);\n"
        "\n"
        "  const isManager = user?.is_superuser ||\n"
        "    (user?.groups || []).some(g => g === 'Admins' || g === 'Managers');\n"
        "\n"
        "  useEffect(() => {\n"
        "    if (!isManager) return;\n"
        "    import('../services/api').then(m => {\n"
        "      const api = m.usersAPI || m.default?.usersAPI;\n"
        "      if (api) api.getAll().then(r => setUsers(r.data?.results || r.data || []));\n"
        "    });\n"
        "  }, [isManager]);\n"
        "\n"
        "  const handleAssignMe = async () => {\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.assignAlertToMe(data.id);\n"
        "      notify('\u062a\u0645 \u0627\u0644\u062a\u062e\u0635\u064a\u0635 \u0644\u0643');\n"
        "      onUpdated();\n"
        "    } catch { notify('\u062e\u0637\u0623 \u0641\u064a \u0627\u0644\u062a\u062e\u0635\u064a\u0635', 'error'); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "\n"
        "  const handleAssignUser = async () => {\n"
        "    if (!selUser) return notify('\u0627\u062e\u062a\u0631 \u0645\u0633\u062a\u062e\u062f\u0645', 'error');\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.assignAlertToUser(data.id, { user_id: selUser });\n"
        "      notify('\u062a\u0645 \u0627\u0644\u062a\u062e\u0635\u064a\u0635');\n"
        "      onUpdated();\n"
        "    } catch { notify('\u062e\u0637\u0623', 'error'); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "\n"
        "  const handleUnassign = async () => {\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.unassignAlert(data.id);\n"
        "      notify('\u062a\u0645 \u0627\u0644\u063a\u0627\u0621 \u0627\u0644\u062a\u062e\u0635\u064a\u0635');\n"
        "      onUpdated();\n"
        "    } catch { notify('\u062e\u0637\u0623', 'error'); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "\n"
        "  return (\n"
        "    <div className=\"mb-4 bg-gray-50 border border-gray-200 rounded-xl px-4 py-3\">\n"
        "      <p className=\"text-xs font-bold text-gray-500 mb-2\">\u0627\u0644\u062a\u062e\u0635\u064a\u0635</p>\n"
        "      <div className=\"flex items-center gap-2 flex-wrap\">\n"
        "        {data.assigned_to_name ? (\n"
        "          <>\n"
        "            <span className=\"text-sm font-bold text-blue-700\">\u0645\u062e\u0635\u0635 \u0644\u0640: {data.assigned_to_name}</span>\n"
        "            <button onClick={handleUnassign} disabled={saving}\n"
        "              className=\"text-xs bg-red-100 hover:bg-red-200 text-red-700 font-bold px-2 py-1 rounded-lg\">\n"
        "              \u0627\u0644\u063a\u0627\u0621 \u0627\u0644\u062a\u062e\u0635\u064a\u0635\n"
        "            </button>\n"
        "          </>\n"
        "        ) : (\n"
        "          <span className=\"text-sm text-gray-400\">\u063a\u064a\u0631 \u0645\u062e\u0635\u0635 \u0644\u0623\u062d\u062f</span>\n"
        "        )}\n"
        "        <button onClick={handleAssignMe} disabled={saving}\n"
        "          className=\"text-xs bg-blue-100 hover:bg-blue-200 text-blue-700 font-bold px-2 py-1 rounded-lg\">\n"
        "          \u062a\u062e\u0635\u064a\u0635 \u0644\u064a\n"
        "        </button>\n"
        "        {isManager && (\n"
        "          <div className=\"flex items-center gap-1\">\n"
        "            <select className=\"text-xs border border-gray-200 rounded-lg px-2 py-1\"\n"
        "              value={selUser} onChange={e => setSelUser(e.target.value)}>\n"
        "              <option value=\"\">\u0627\u062e\u062a\u0631 \u0645\u0633\u062a\u062e\u062f\u0645...</option>\n"
        "              {users.map(u => <option key={u.id} value={u.id}>{u.username}</option>)}\n"
        "            </select>\n"
        "            <button onClick={handleAssignUser} disabled={saving || !selUser}\n"
        "              className=\"text-xs bg-purple-100 hover:bg-purple-200 text-purple-700 font-bold px-2 py-1 rounded-lg\">\n"
        "              \u062a\u062e\u0635\u064a\u0635\n"
        "            </button>\n"
        "          </div>\n"
        "        )}\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── AlertsPanel ────────────────────────────────────────────────\n"
        "function AlertsPanel() {\n"
        "  const [alerts, setAlerts]       = useState([]);\n"
        "  const [loading, setLoading]     = useState(true);\n"
        "  const [filter, setFilter]       = useState('unresolved');\n"
        "  const [selected, setSelected]   = useState(null);\n"
        "  const [toast, setToast]         = useState(null);\n"
        "  const [suppliers, setSuppliers] = useState([]);\n"
        "  const notify = (msg, type='success') => { setToast({msg,type}); setTimeout(()=>setToast(null),3500); };\n"
        "\n"
        "  const load = useCallback(async () => {\n"
        "    setLoading(true);\n"
        "    try {\n"
        "      const params = {};\n"
        "      if (filter === 'unresolved') params.is_resolved = false;\n"
        "      else if (filter === 'resolved') params.is_resolved = true;\n"
        "      else if (filter === 'critical') { params.is_resolved = false; params.priority = 'critical'; }\n"
        "      else if (filter === 'out') { params.is_resolved = false; params.alert_type = 'out'; }\n"
        "      const [a, s] = await Promise.all([\n"
        "        inventoryAPI.getAlerts(params),\n"
        "        inventoryAPI.getSuppliers(),\n"
        "      ]);\n"
        "      setAlerts(a.data?.results || a.data || []);\n"
        "      setSuppliers(s.data?.results || s.data || []);\n"
        "    } catch { /**/ } finally { setLoading(false); }\n"
        "  }, [filter]);\n"
        "\n"
        "  useEffect(() => { load(); }, [load]);\n"
        "\n"
        "  const handleGenerate = async () => {\n"
        "    try {\n"
        "      const r = await inventoryAPI.checkAndGenerateAlerts({ threshold: 10 });\n"
        "      notify('\u062a\u0645 \u0625\u0646\u0634\u0627\u0621 ' + r.data.created_alerts + ' \u062a\u0646\u0628\u064a\u0647 \u062c\u062f\u064a\u062f');\n"
        "      load();\n"
        "    } catch { notify('\u062e\u0637\u0623 \u0641\u064a \u062a\u0648\u0644\u064a\u062f \u0627\u0644\u062a\u0646\u0628\u064a\u0647\u0627\u062a', 'error'); }\n"
        "  };\n"
        "\n"
        "  const filters = [\n"
        "    { key: 'unresolved', label: '\u063a\u064a\u0631 \u0645\u062d\u0644\u0648\u0644\u0629' },\n"
        "    { key: 'out',        label: '\u0646\u0641\u0627\u062f'     },\n"
        "    { key: 'critical',   label: '\u062d\u0631\u062c\u0629'     },\n"
        "    { key: 'resolved',   label: '\u0645\u062d\u0644\u0648\u0644\u0629'   },\n"
        "    { key: 'all',        label: '\u0627\u0644\u0643\u0644'        },\n"
        "  ];\n"
        "\n"
        "  if (loading) return <Spinner />;\n"
        "  return (\n"
        "    <div className=\"space-y-4\">\n"
        "      {toast && <Toast msg={toast.msg} type={toast.type} />}\n"
        "      <div className=\"flex flex-wrap gap-3 items-center justify-between\">\n"
        "        <div className=\"flex gap-2 flex-wrap\">\n"
        "          {filters.map(f => (\n"
        "            <button key={f.key} onClick={() => setFilter(f.key)}\n"
        "              className={`px-3 py-1.5 rounded-xl text-sm font-bold transition ${\n"
        "                filter === f.key ? 'bg-blue-600 text-white' : 'bg-white border text-gray-600 hover:bg-gray-50'\n"
        "              }`}>{f.label}</button>\n"
        "          ))}\n"
        "        </div>\n"
        "        <div className=\"flex gap-2\">\n"
        "          <button onClick={load} className=\"bg-white border text-gray-600 hover:bg-gray-50"
        " font-bold px-3 py-1.5 rounded-xl text-sm\">\u062a\u062d\u062f\u064a\u062b</button>\n"
        "          <button onClick={handleGenerate}\n"
        "            className=\"bg-yellow-500 hover:bg-yellow-600 text-white font-bold px-4 py-1.5 rounded-xl text-sm\">\n"
        "            \u0641\u062d\u0635 \u0648\u062a\u0648\u0644\u064a\u062f \u0627\u0644\u062a\u0646\u0628\u064a\u0647\u0627\u062a\n"
        "          </button>\n"
        "        </div>\n"
        "      </div>\n"
        "      {alerts.length === 0 ? (\n"
        "        <div className=\"bg-white rounded-2xl border border-gray-200 p-12 text-center text-gray-400\">\n"
        "          <p className=\"font-bold\">\u0644\u0627 \u062a\u0648\u062c\u062f \u062a\u0646\u0628\u064a\u0647\u0627\u062a</p>\n"
        "        </div>\n"
        "      ) : (\n"
        "        <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\">\n"
        "          {alerts.map(a => (\n"
        "            <AlertCard key={a.id} alert={a} onOpen={setSelected} />\n"
        "          ))}\n"
        "        </div>\n"
        "      )}\n"
        "      {selected && (\n"
        "        <AlertTicketModal\n"
        "          alert={selected}\n"
        "          suppliers={suppliers}\n"
        "          onClose={() => setSelected(null)}\n"
        "          onUpdated={() => { setSelected(null); load(); }}\n"
        "          notify={notify}\n"
        "        />\n"
        "      )}\n"
        "    </div>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── AlertTicketModal ───────────────────────────────────────────\n"
        "function AlertTicketModal({ alert, suppliers, onClose, onUpdated, notify }) {\n"
        "  const [data, setData]     = useState(alert);\n"
        "  const [noteForm, setNote] = useState({ note_type:'note', text:'', cost:'', expected_date:'', delay_reason:'', supplier_name:'' });\n"
        "  const [poForm, setPo]     = useState({ supplier:'', quantity:1, unit_cost:'', expected_date:'', notes:'' });\n"
        "  const [tab, setTab]       = useState('timeline');\n"
        "  const [saving, setSaving] = useState(false);\n"
        "\n"
        "  const reload = async () => {\n"
        "    try { const r = await inventoryAPI.getAlert(data.id); setData(r.data); } catch {}\n"
        "  };\n"
        "\n"
        "  const handleAddNote = async () => {\n"
        "    if (!noteForm.text.trim()) return notify('\u0627\u0643\u062a\u0628 \u0646\u0635 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629', 'error');\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.addAlertNote(data.id, noteForm);\n"
        "      setNote({ note_type:'note', text:'', cost:'', expected_date:'', delay_reason:'', supplier_name:'' });\n"
        "      await reload();\n"
        "      notify('\u062a\u0645\u062a \u0625\u0636\u0627\u0641\u0629 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629');\n"
        "    } catch(e) { notify('\u062e\u0637\u0623: '+(e?.response?.data?.error||JSON.stringify(e?.response?.data)||'\u062e\u0637\u0623'), 'error'); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "\n"
        "  const handleCreatePO = async () => {\n"
        "    if (!poForm.quantity || !poForm.unit_cost) return notify('\u0627\u0644\u0643\u0645\u064a\u0629 \u0648\u0627\u0644\u062a\u0643\u0644\u0641\u0629 \u0645\u0637\u0644\u0648\u0628\u0627\u0646', 'error');\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.createPoFromAlert(data.id, {\n"
        "        supplier: poForm.supplier || null,\n"
        "        quantity: Number(poForm.quantity),\n"
        "        unit_cost: Number(poForm.unit_cost),\n"
        "        expected_date: poForm.expected_date || null,\n"
        "        notes: poForm.notes,\n"
        "      });\n"
        "      notify('\u062a\u0645 \u0625\u0646\u0634\u0627\u0621 \u0639\u0631\u0636 \u0627\u0644\u0634\u0631\u0627\u0621 \u0648\u0631\u0628\u0637\u0647 \u0628\u0627\u0644\u062a\u0646\u0628\u064a\u0647');\n"
        "      await reload();\n"
        "      setPo({ supplier:'', quantity:1, unit_cost:'', expected_date:'', notes:'' });\n"
        "    } catch(e) { notify('\u062e\u0637\u0623: '+(e?.response?.data?.error||JSON.stringify(e?.response?.data)||'\u062e\u0637\u0623'), 'error'); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "\n"
        "  const handleResolve = async () => {\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.resolveAlert(data.id, { note: '\u062a\u0645 \u0627\u0644\u062d\u0644 \u064a\u062f\u0648\u064a\u0627\u064b' });\n"
        "      notify('\u062a\u0645 \u062d\u0644 \u0627\u0644\u062a\u0646\u0628\u064a\u0647');\n"
        "      onUpdated();\n"
        "    } catch(e) { notify('\u062e\u0637\u0623: '+(e?.response?.data?.error||JSON.stringify(e?.response?.data)||'\u062e\u0637\u0623'), 'error'); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "\n"
        "  const pr = priorityConfig[data.priority] || priorityConfig.medium;\n"
        "  const st = ticketStatusConfig[data.ticket_status] || ticketStatusConfig.open;\n"
        "\n"
        "  return (\n"
        "    <Modal title={'\u062a\u0630\u0643\u0631\u0629: ' + data.product_name} onClose={onClose}>\n"
        "      {/* badges */}\n"
        "      <div className=\"flex flex-wrap gap-2 mb-3\">\n"
        "        <span className={`text-xs font-bold px-2 py-1 rounded-full ${st.color}`}>{st.label}</span>\n"
        "        <span className={`text-xs font-bold px-2 py-1 rounded-full ${pr.color}`}>{pr.label}</span>\n"
        "        <span className={`text-xs font-bold px-2 py-1 rounded-full ${\n"
        "          data.alert_type==='out'?'bg-red-100 text-red-700':'bg-yellow-100 text-yellow-700'}`}>\n"
        "          {data.alert_type==='out'?'\u0646\u0641\u0627\u062f \u0627\u0644\u0645\u062e\u0632\u0648\u0646':'\u0645\u062e\u0632\u0648\u0646 \u0645\u0646\u062e\u0641\u0636'}\n"
        "        </span>\n"
        "        <span className=\"text-xs font-bold px-2 py-1 rounded-full bg-gray-100 text-gray-700\">\n"
        "          \u0627\u0644\u0645\u062e\u0632\u0648\u0646: {data.product_current_stock ?? data.current_stock} \u0648\u062d\u062f\u0629\n"
        "        </span>\n"
        "        {data.created_by_name && (\n"
        "          <span className=\"text-xs font-bold px-2 py-1 rounded-full bg-gray-100 text-gray-600\">\n"
        "            \u0628\u0648\u0627\u0633\u0637\u0629: {data.created_by_name}\n"
        "          </span>\n"
        "        )}\n"
        "      </div>\n"
        "\n"
        "      {/* عروض الشراء المرتبطة */}\n"
        "      {data.linked_pos_data && data.linked_pos_data.length > 0 && (\n"
        "        <div className=\"mb-3 bg-blue-50 border border-blue-200 rounded-xl p-3\">\n"
        "          <p className=\"text-xs font-bold text-blue-700 mb-2\">\u0639\u0631\u0648\u0636 \u0627\u0644\u0634\u0631\u0627\u0621 ({data.linked_pos_data.length}):</p>\n"
        "          {data.linked_pos_data.map(po => (\n"
        "            <div key={po.id} className=\"flex justify-between text-xs text-blue-600 py-1 border-t border-blue-100\">\n"
        "              <span className=\"font-bold\">{po.reference_number}</span>\n"
        "              <span>{po.status}</span>\n"
        "              {po.expected_date && <span>{po.expected_date}</span>}\n"
        "            </div>\n"
        "          ))}\n"
        "        </div>\n"
        "      )}\n"
        "\n"
        "      {/* التخصيص */}\n"
        "      <AssignSection data={data} onUpdated={async () => { await reload(); onUpdated && onUpdated(); }} notify={notify} />\n"
        "\n"
        "      {/* تبويبات */}\n"
        "      <div className=\"flex gap-2 border-b mb-4\">\n"
        "        {[\n"
        "          {key:'timeline', label:'\u0627\u0644\u0633\u062c\u0644'},\n"
        "          {key:'add_note', label:'\u0625\u0636\u0627\u0641\u0629'},\n"
        "          {key:'create_po',label:'\u0639\u0631\u0636 \u0634\u0631\u0627\u0621'},\n"
        "          {key:'resolve',  label:'\u062d\u0644'},\n"
        "        ].map(t => (\n"
        "          <button key={t.key} onClick={() => setTab(t.key)}\n"
        "            className={`px-3 py-2 text-sm font-bold border-b-2 transition -mb-px ${\n"
        "              tab===t.key?'border-blue-600 text-blue-600':'border-transparent text-gray-500 hover:text-gray-700'\n"
        "            }`}>{t.label}</button>\n"
        "        ))}\n"
        "      </div>\n"
        "\n"
        "      {/* السجل */}\n"
        "      {tab === 'timeline' && (\n"
        "        <div className=\"space-y-3 max-h-72 overflow-y-auto\">\n"
        "          {(!data.notes || data.notes.length === 0) ? (\n"
        "            <p className=\"text-center text-gray-400 py-6\">\u0644\u0627 \u062a\u0648\u062c\u062f \u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0628\u0639\u062f</p>\n"
        "          ) : (\n"
        "            data.notes.map(n => {\n"
        "              const nc = noteTypeConfig[n.note_type] || noteTypeConfig.note;\n"
        "              return (\n"
        "                <div key={n.id} className={`rounded-xl border p-3 ${nc.color}`}>\n"
        "                  <div className=\"flex items-center justify-between mb-1\">\n"
        "                    <span className=\"text-xs font-bold\">{nc.icon} {nc.label}</span>\n"
        "                    <span className=\"text-xs text-gray-400\">{n.user_name} \u00b7 {n.created_at?.split('T')[0]}</span>\n"
        "                  </div>\n"
        "                  <p className=\"text-sm text-gray-700\">{n.text}</p>\n"
        "                  {n.cost && <p className=\"text-xs text-green-700 mt-1 font-bold\">\u062a\u0643\u0644\u0641\u0629: {fmt(n.cost)}</p>}\n"
        "                  {n.expected_date && <p className=\"text-xs text-blue-700 mt-1\">\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0633\u062a\u0644\u0627\u0645: {n.expected_date}</p>}\n"
        "                  {n.delay_reason && <p className=\"text-xs text-orange-700 mt-1\">\u0633\u0628\u0628 \u0627\u0644\u062a\u0623\u062e\u064a\u0631: {n.delay_reason}</p>}\n"
        "                  {n.supplier_name && <p className=\"text-xs text-gray-600 mt-1\">\u0627\u0644\u0645\u0648\u0631\u062f: {n.supplier_name}</p>}\n"
        "                </div>\n"
        "              );\n"
        "            })\n"
        "          )}\n"
        "        </div>\n"
        "      )}\n"
        "\n"
        "      {/* إضافة ملاحظة */}\n"
        "      {tab === 'add_note' && (\n"
        "        <div className=\"space-y-3\">\n"
        "          <Field label=\"\u0646\u0648\u0639 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629\">\n"
        "            <select className={INP} value={noteForm.note_type} onChange={e=>setNote({...noteForm,note_type:e.target.value})}>\n"
        "              {Object.entries(noteTypeConfig).map(([k,v]) => <option key={k} value={k}>{v.label}</option>)}\n"
        "            </select>\n"
        "          </Field>\n"
        "          <Field label=\"\u0627\u0644\u0646\u0635 *\">\n"
        "            <textarea className={INP} rows={3} value={noteForm.text}\n"
        "              onChange={e=>setNote({...noteForm,text:e.target.value})} placeholder=\"\u0627\u0643\u062a\u0628 \u0645\u0644\u0627\u062d\u0638\u062a\u0643 \u0647\u0646\u0627...\" />\n"
        "          </Field>\n"
        "          {noteForm.note_type === 'quote' && (\n"
        "            <>\n"
        "              <div className=\"grid grid-cols-2 gap-3\">\n"
        "                <Field label=\"\u0627\u0644\u062a\u0643\u0644\u0641\u0629\">\n"
        "                  <input type=\"number\" className={INP} value={noteForm.cost}\n"
        "                    onChange={e=>setNote({...noteForm,cost:e.target.value})} placeholder=\"0.00\" />\n"
        "                </Field>\n"
        "                <Field label=\"\u0627\u0633\u0645 \u0627\u0644\u0645\u0648\u0631\u062f\">\n"
        "                  <input type=\"text\" className={INP} value={noteForm.supplier_name}\n"
        "                    onChange={e=>setNote({...noteForm,supplier_name:e.target.value})} />\n"
        "                </Field>\n"
        "              </div>\n"
        "              <Field label=\"\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0633\u062a\u0644\u0627\u0645 \u0627\u0644\u0645\u062a\u0648\u0642\u0639\">\n"
        "                <input type=\"date\" className={INP} value={noteForm.expected_date}\n"
        "                  onChange={e=>setNote({...noteForm,expected_date:e.target.value})} />\n"
        "              </Field>\n"
        "            </>\n"
        "          )}\n"
        "          {noteForm.note_type === 'delay' && (\n"
        "            <Field label=\"\u0633\u0628\u0628 \u0627\u0644\u062a\u0623\u062e\u064a\u0631\">\n"
        "              <textarea className={INP} rows={2} value={noteForm.delay_reason}\n"
        "                onChange={e=>setNote({...noteForm,delay_reason:e.target.value})} />\n"
        "            </Field>\n"
        "          )}\n"
        "          <button onClick={handleAddNote} disabled={saving}\n"
        "            className=\"w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 rounded-xl text-sm disabled:opacity-50\">\n"
        "            {saving ? '...' : '\u0625\u0636\u0627\u0641\u0629 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629'}\n"
        "          </button>\n"
        "        </div>\n"
        "      )}\n"
        "\n"
        "      {/* إنشاء عرض شراء */}\n"
        "      {tab === 'create_po' && (\n"
        "        <div className=\"space-y-3\">\n"
        "          <div className=\"grid grid-cols-2 gap-3\">\n"
        "            <Field label=\"\u0627\u0644\u0645\u0648\u0631\u062f\">\n"
        "              <select className={INP} value={poForm.supplier} onChange={e=>setPo({...poForm,supplier:e.target.value})}>\n"
        "                <option value=\"\">\u0628\u062f\u0648\u0646 \u0645\u0648\u0631\u062f</option>\n"
        "                {suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}\n"
        "              </select>\n"
        "            </Field>\n"
        "            <Field label=\"\u0627\u0644\u0643\u0645\u064a\u0629 *\">\n"
        "              <input type=\"number\" min={1} className={INP} value={poForm.quantity}\n"
        "                onChange={e=>setPo({...poForm,quantity:e.target.value})} />\n"
        "            </Field>\n"
        "            <Field label=\"\u062a\u0643\u0644\u0641\u0629 \u0627\u0644\u0648\u062d\u062f\u0629 *\">\n"
        "              <input type=\"number\" step=\"0.01\" className={INP} value={poForm.unit_cost}\n"
        "                onChange={e=>setPo({...poForm,unit_cost:e.target.value})} />\n"
        "            </Field>\n"
        "            <Field label=\"\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0633\u062a\u0644\u0627\u0645 \u0627\u0644\u0645\u062a\u0648\u0642\u0639\">\n"
        "              <input type=\"date\" className={INP} value={poForm.expected_date}\n"
        "                onChange={e=>setPo({...poForm,expected_date:e.target.value})} />\n"
        "            </Field>\n"
        "          </div>\n"
        "          <Field label=\"\u0645\u0644\u0627\u062d\u0638\u0627\u062a\">\n"
        "            <input type=\"text\" className={INP} value={poForm.notes}\n"
        "              onChange={e=>setPo({...poForm,notes:e.target.value})} placeholder=\"\u0627\u062e\u062a\u064a\u0627\u0631\u064a\" />\n"
        "          </Field>\n"
        "          <button onClick={handleCreatePO} disabled={saving}\n"
        "            className=\"w-full bg-green-600 hover:bg-green-700 text-white font-bold py-2 rounded-xl text-sm disabled:opacity-50\">\n"
        "            {saving ? '...' : '\u0625\u0646\u0634\u0627\u0621 \u0639\u0631\u0636 \u0634\u0631\u0627\u0621'}\n"
        "          </button>\n"
        "        </div>\n"
        "      )}\n"
        "\n"
        "      {/* حل التذكرة */}\n"
        "      {tab === 'resolve' && (\n"
        "        <div className=\"space-y-3\">\n"
        "          {data.is_resolved ? (\n"
        "            <div className=\"bg-green-50 border border-green-200 rounded-xl p-4 text-sm text-green-700 font-bold text-center\">\n"
        "              \u0647\u0630\u0647 \u0627\u0644\u062a\u0630\u0643\u0631\u0629 \u0645\u062d\u0644\u0648\u0644\u0629 \u0628\u0627\u0644\u0641\u0639\u0644\n"
        "            </div>\n"
        "          ) : (\n"
        "            <>\n"
        "              {data.linked_pos_data && data.linked_pos_data.some(p => p.status !== 'received' && p.status !== 'cancelled') && (\n"
        "                <div className=\"bg-orange-50 border border-orange-200 rounded-xl p-3 text-sm text-orange-700 font-bold\">\n"
        "                  \u0628\u0639\u0636 \u0639\u0631\u0648\u0636 \u0627\u0644\u0634\u0631\u0627\u0621 \u0644\u0645 \u062a\u064f\u0633\u062a\u0644\u0645 \u0628\u0639\u062f. \u062a\u0623\u0643\u062f \u0645\u0646 \u0627\u0644\u0627\u0633\u062a\u0644\u0627\u0645 \u0623\u0648\u0644\u0627\u064b.\n"
        "                </div>\n"
        "              )}\n"
        "              <button onClick={handleResolve} disabled={saving}\n"
        "                className=\"w-full bg-green-600 hover:bg-green-700 text-white font-bold py-2 rounded-xl text-sm disabled:opacity-50\">\n"
        "                {saving ? '...' : '\u062a\u0623\u0643\u064a\u062f \u0627\u0644\u062d\u0644 \u0648\u0625\u063a\u0644\u0627\u0642 \u0627\u0644\u062a\u0630\u0643\u0631\u0629'}\n"
        "              </button>\n"
        "            </>\n"
        "          )}\n"
        "        </div>\n"
        "      )}\n"
        "    </Modal>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── PurchaseOrdersPanel ────────────────────────────────────────\n"
        "function PurchaseOrdersPanel() {\n"
        "  const [orders, setOrders]       = useState([]);\n"
        "  const [suppliers, setSuppliers] = useState([]);\n"
        "  const [products, setProducts]   = useState([]);\n"
        "  const [loading, setLoading]     = useState(true);\n"
        "  const [showForm, setShowForm]   = useState(false);\n"
        "  const [toast, setToast]         = useState(null);\n"
        "  const notify = (msg, type='success') => { setToast({msg,type}); setTimeout(()=>setToast(null),3500); };\n"
        "\n"
        "  const load = useCallback(async () => {\n"
        "    setLoading(true);\n"
        "    try {\n"
        "      const [o,s,p] = await Promise.all([\n"
        "        inventoryAPI.getPurchaseOrders(),\n"
        "        inventoryAPI.getSuppliers(),\n"
        "        productsAPI.getAll({ page_size:200 }),\n"
        "      ]);\n"
        "      setOrders(o.data?.results||o.data||[]);\n"
        "      setSuppliers(s.data?.results||s.data||[]);\n"
        "      setProducts(p.data?.results||p.data||[]);\n"
        "    } catch {/**/} finally { setLoading(false); }\n"
        "  }, []);\n"
        "\n"
        "  useEffect(() => { load(); }, [load]);\n"
        "\n"
        "  const handleCancel = async (id) => {\n"
        "    if (!window.confirm('\u0647\u0644 \u0623\u0646\u062a \u0645\u062a\u0623\u0643\u062f \u0645\u0646 \u0627\u0644\u0625\u0644\u063a\u0627\u0621\u061f')) return;\n"
        "    try { await inventoryAPI.cancelPurchaseOrder(id); notify('\u062a\u0645 \u0627\u0644\u0625\u0644\u063a\u0627\u0621'); load(); }\n"
        "    catch(e) { notify('\u062e\u0637\u0623: '+(e?.response?.data?.error||'\u062e\u0637\u0623'),'error'); }\n"
        "  };\n"
        "\n"
        "  if (loading) return <Spinner />;\n"
        "  return (\n"
        "    <div className=\"space-y-4\">\n"
        "      {toast && <Toast msg={toast.msg} type={toast.type} />}\n"
        "      <div className=\"flex justify-between items-center\">\n"
        "        <h2 className=\"font-black text-gray-700 text-lg\">\u0623\u0648\u0627\u0645\u0631 \u0627\u0644\u0634\u0631\u0627\u0621</h2>\n"
        "        <button onClick={() => setShowForm(true)}\n"
        "          className=\"bg-blue-600 hover:bg-blue-700 text-white font-bold px-4 py-2 rounded-xl text-sm\">\n"
        "          \u0625\u0646\u0634\u0627\u0621 \u0623\u0645\u0631 \u0634\u0631\u0627\u0621\n"
        "        </button>\n"
        "      </div>\n"
        "      <div className=\"bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden\">\n"
        "        <table className=\"w-full text-sm\">\n"
        "          <thead><tr className=\"bg-gray-50 text-gray-500 text-right\">\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0631\u0642\u0645 \u0627\u0644\u0645\u0631\u062c\u0639</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u0645\u0648\u0631\u062f</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u062d\u0627\u0644\u0629</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u062a\u0627\u0631\u064a\u062e</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0625\u062c\u0631\u0627\u0621\u0627\u062a</th>\n"
        "          </tr></thead>\n"
        "          <tbody>\n"
        "            {orders.length===0 && (\n"
        "              <tr><td colSpan={6} className=\"text-center py-8 text-gray-400\">\u0644\u0627 \u062a\u0648\u062c\u062f \u0623\u0648\u0627\u0645\u0631 \u0634\u0631\u0627\u0621</td></tr>\n"
        "            )}\n"
        "            {orders.map(o => (\n"
        "              <tr key={o.id} className=\"border-t hover:bg-gray-50\">\n"
        "                <td className=\"px-4 py-3 font-bold text-blue-700\">{o.reference_number}</td>\n"
        "                <td className=\"px-4 py-3\">{o.supplier_name||'\u2014'}</td>\n"
        "                <td className=\"px-4 py-3\"><Badge label={o.status} color={statusColor(o.status)} /></td>\n"
        "                <td className=\"px-4 py-3 font-bold\">{fmt(o.total_cost)}</td>\n"
        "                <td className=\"px-4 py-3 text-gray-500\">{o.created_at?.split('T')[0]}</td>\n"
        "                <td className=\"px-4 py-3\">\n"
        "                  {o.status!=='received'&&o.status!=='cancelled' && (\n"
        "                    <button onClick={() => handleCancel(o.id)}\n"
        "                      className=\"bg-red-100 hover:bg-red-200 text-red-700 text-xs font-bold px-3 py-1 rounded-lg\">\n"
        "                      \u0625\u0644\u063a\u0627\u0621\n"
        "                    </button>\n"
        "                  )}\n"
        "                </td>\n"
        "              </tr>\n"
        "            ))}\n"
        "          </tbody>\n"
        "        </table>\n"
        "      </div>\n"
        "      {showForm && (\n"
        "        <NewOrderModal suppliers={suppliers} products={products}\n"
        "          onClose={() => setShowForm(false)}\n"
        "          onSaved={() => { setShowForm(false); load(); notify('\u062a\u0645 \u0625\u0646\u0634\u0627\u0621 \u0623\u0645\u0631 \u0627\u0644\u0634\u0631\u0627\u0621'); }}\n"
        "          onError={(msg) => notify('\u062e\u0637\u0623: '+msg,'error')} />\n"
        "      )}\n"
        "    </div>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── NewOrderModal ──────────────────────────────────────────────\n"
        "function NewOrderModal({ suppliers, products, onClose, onSaved, onError }) {\n"
        "  const [form, setForm] = useState({\n"
        "    reference_number: 'PO-'+Date.now(),\n"
        "    supplier:'', expected_date:'', notes:'', status:'ordered',\n"
        "  });\n"
        "  const [items, setItems]   = useState([{ product:'', quantity:1, unit_cost:'' }]);\n"
        "  const [saving, setSaving] = useState(false);\n"
        "  const addItem    = () => setItems([...items,{ product:'', quantity:1, unit_cost:'' }]);\n"
        "  const removeItem = (i) => setItems(items.filter((_,idx)=>idx!==i));\n"
        "  const updateItem = (i,field,val) => { const n=[...items]; n[i]={...n[i],[field]:val}; setItems(n); };\n"
        "  const handleSave = async () => {\n"
        "    if (!form.reference_number) return onError('\u0631\u0642\u0645 \u0627\u0644\u0645\u0631\u062c\u0639 \u0645\u0637\u0644\u0648\u0628');\n"
        "    const valid = items.filter(it=>it.product&&it.quantity>0&&it.unit_cost);\n"
        "    if (!valid.length) return onError('\u0623\u0636\u0641 \u0645\u0646\u062a\u062c\u0627\u064b \u0648\u0627\u062d\u062f\u0627\u064b \u0639\u0644\u0649 \u0627\u0644\u0623\u0642\u0644');\n"
        "    setSaving(true);\n"
        "    try {\n"
        "      await inventoryAPI.createPurchaseOrder({\n"
        "        ...form, supplier: form.supplier||null,\n"
        "        items: valid.map(it=>({...it, quantity:Number(it.quantity), unit_cost:Number(it.unit_cost)}))\n"
        "      });\n"
        "      onSaved();\n"
        "    } catch(e) { onError(JSON.stringify(e?.response?.data||'\u062e\u0637\u0623')); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n"
        "  return (\n"
        "    <Modal title=\"\u0623\u0645\u0631 \u0634\u0631\u0627\u0621 \u062c\u062f\u064a\u062f\" onClose={onClose}>\n"
        "      <div className=\"space-y-3\">\n"
        "        <div className=\"grid grid-cols-2 gap-3\">\n"
        "          <Field label=\"\u0631\u0642\u0645 \u0627\u0644\u0645\u0631\u062c\u0639 *\">\n"
        "            <input className={INP} value={form.reference_number}\n"
        "              onChange={e=>setForm({...form,reference_number:e.target.value})} />\n"
        "          </Field>\n"
        "          <Field label=\"\u0627\u0644\u0645\u0648\u0631\u062f\">\n"
        "            <select className={INP} value={form.supplier}\n"
        "              onChange={e=>setForm({...form,supplier:e.target.value})}>\n"
        "              <option value=\"\">\u0628\u062f\u0648\u0646 \u0645\u0648\u0631\u062f</option>\n"
        "              {suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}\n"
        "            </select>\n"
        "          </Field>\n"
        "          <Field label=\"\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0633\u062a\u0644\u0627\u0645\">\n"
        "            <input type=\"date\" className={INP} value={form.expected_date}\n"
        "              onChange={e=>setForm({...form,expected_date:e.target.value})} />\n"
        "          </Field>\n"
        "          <Field label=\"\u0627\u0644\u062d\u0627\u0644\u0629\">\n"
        "            <select className={INP} value={form.status}\n"
        "              onChange={e=>setForm({...form,status:e.target.value})}>\n"
        "              <option value=\"draft\">\u0645\u0633\u0648\u062f\u0629</option>\n"
        "              <option value=\"ordered\">\u062a\u0645 \u0627\u0644\u0637\u0644\u0628</option>\n"
        "            </select>\n"
        "          </Field>\n"
        "        </div>\n"
        "        <Field label=\"\u0645\u0644\u0627\u062d\u0638\u0627\u062a\">\n"
        "          <textarea className={INP} rows={2} value={form.notes}\n"
        "            onChange={e=>setForm({...form,notes:e.target.value})} />\n"
        "        </Field>\n"
        "        <div>\n"
        "          <div className=\"flex justify-between items-center mb-2\">\n"
        "            <span className=\"font-bold text-gray-700 text-sm\">\u0627\u0644\u0645\u0646\u062a\u062c\u0627\u062a</span>\n"
        "            <button onClick={addItem} className=\"text-blue-600 text-sm font-bold hover:underline\">+ \u0625\u0636\u0627\u0641\u0629</button>\n"
        "          </div>\n"
        "          {items.map((item,i) => (\n"
        "            <div key={i} className=\"flex gap-2 mb-2 items-end\">\n"
        "              <div className=\"flex-1\">\n"
        "                <select className={INP+' text-xs'} value={item.product}\n"
        "                  onChange={e=>updateItem(i,'product',e.target.value)}>\n"
        "                  <option value=\"\">\u0627\u062e\u062a\u0631 \u0645\u0646\u062a\u062c</option>\n"
        "                  {products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}\n"
        "                </select>\n"
        "              </div>\n"
        "              <div className=\"w-20\">\n"
        "                <input type=\"number\" className={INP+' text-xs text-center'} placeholder=\"\u0643\u0645\u064a\u0629\"\n"
        "                  min={1} value={item.quantity} onChange={e=>updateItem(i,'quantity',e.target.value)} />\n"
        "              </div>\n"
        "              <div className=\"w-24\">\n"
        "                <input type=\"number\" className={INP+' text-xs text-center'} placeholder=\"\u062a\u0643\u0644\u0641\u0629\"\n"
        "                  min={0} step=\"0.01\" value={item.unit_cost} onChange={e=>updateItem(i,'unit_cost',e.target.value)} />\n"
        "              </div>\n"
        "              <button onClick={()=>removeItem(i)}\n"
        "                className=\"text-red-500 font-black text-xl leading-none mb-1\">\u00d7</button>\n"
        "            </div>\n"
        "          ))}\n"
        "        </div>\n"
        "        <div className=\"flex gap-3 justify-end pt-2\">\n"
        "          <button onClick={onClose} className=\"px-4 py-2 rounded-xl border font-bold text-sm\">\u0625\u0644\u063a\u0627\u0621</button>\n"
        "          <button onClick={handleSave} disabled={saving}\n"
        "            className=\"bg-blue-600 hover:bg-blue-700 text-white font-bold px-5 py-2 rounded-xl text-sm\">\n"
        "            {saving?'...':'\u062d\u0641\u0638'}\n"
        "          </button>\n"
        "        </div>\n"
        "      </div>\n"
        "    </Modal>\n"
        "  );\n"
        "}\n"
        "\n"
        "// ── SuppliersPanel ─────────────────────────────────────────────\n"
        "function SuppliersPanel() {\n"
        "  const [suppliers, setSuppliers] = useState([]);\n"
        "  const [loading, setLoading]     = useState(true);\n"
        "  const [toast, setToast]         = useState(null);\n"
        "  const [showForm, setShowForm]   = useState(false);\n"
        "  const [editing, setEditing]     = useState(null);\n"
        "  const notify = (msg, type='success') => { setToast({msg,type}); setTimeout(()=>setToast(null),3500); };\n"
        "\n"
        "  const load = useCallback(async () => {\n"
        "    setLoading(true);\n"
        "    try {\n"
        "      const r = await inventoryAPI.getSuppliers();\n"
        "      setSuppliers(r.data?.results || r.data || []);\n"
        "    } catch {/**/} finally { setLoading(false); }\n"
        "  }, []);\n"
        "\n"
        "  useEffect(() => { load(); }, [load]);\n"
        "\n"
        "  const handleSave = async (form) => {\n"
        "    try {\n"
        "      if (editing) {\n"
        "        await inventoryAPI.updateSupplier(editing.id, form);\n"
        "        notify('\u062a\u0645 \u0627\u0644\u062a\u0639\u062f\u064a\u0644');\n"
        "      } else {\n"
        "        await inventoryAPI.createSupplier(form);\n"
        "        notify('\u062a\u0645 \u0627\u0644\u0625\u0636\u0627\u0641\u0629');\n"
        "      }\n"
        "      setShowForm(false); setEditing(null); load();\n"
        "    } catch { notify('\u062e\u0637\u0623', 'error'); }\n"
        "  };\n"
        "\n"
        "  if (loading) return <Spinner />;\n"
        "  return (\n"
        "    <div className=\"space-y-4\">\n"
        "      {toast && <Toast msg={toast.msg} type={toast.type} />}\n"
        "      <div className=\"flex justify-between items-center\">\n"
        "        <h2 className=\"font-black text-gray-700 text-lg\">\u0627\u0644\u0645\u0648\u0631\u062f\u0648\u0646</h2>\n"
        "        <button onClick={() => { setEditing(null); setShowForm(true); }}\n"
        "          className=\"bg-blue-600 hover:bg-blue-700 text-white font-bold px-4 py-2 rounded-xl text-sm\">\n"
        "          \u0625\u0636\u0627\u0641\u0629 \u0645\u0648\u0631\u062f\n"
        "        </button>\n"
        "      </div>\n"
        "      <div className=\"bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden\">\n"
        "        <table className=\"w-full text-sm\">\n"
        "          <thead><tr className=\"bg-gray-50 text-gray-500 text-right\">\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u0627\u0633\u0645</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u0647\u0627\u062a\u0641</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u0628\u0631\u064a\u062f</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0627\u0644\u0637\u0644\u0628\u0627\u062a</th>\n"
        "            <th className=\"px-4 py-3 font-bold\">\u0625\u062c\u0631\u0627\u0621\u0627\u062a</th>\n"
        "          </tr></thead>\n"
        "          <tbody>\n"
        "            {suppliers.length===0 && (\n"
        "              <tr><td colSpan={5} className=\"text-center py-8 text-gray-400\">\u0644\u0627 \u064a\u0648\u062c\u062f \u0645\u0648\u0631\u062f\u0648\u0646</td></tr>\n"
        "            )}\n"
        "            {suppliers.map(s => (\n"
        "              <tr key={s.id} className=\"border-t hover:bg-gray-50\">\n"
        "                <td className=\"px-4 py-3 font-bold\">{s.name}</td>\n"
        "                <td className=\"px-4 py-3\">{s.phone||'-'}</td>\n"
        "                <td className=\"px-4 py-3\">{s.email||'-'}</td>\n"
        "                <td className=\"px-4 py-3\">{s.orders_count}</td>\n"
        "                <td className=\"px-4 py-3\">\n"
        "                  <button onClick={() => { setEditing(s); setShowForm(true); }}\n"
        "                    className=\"text-xs bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold px-2 py-1 rounded-lg\">\n"
        "                    \u062a\u0639\u062f\u064a\u0644\n"
        "                  </button>\n"
        "                </td>\n"
        "              </tr>\n"
        "            ))}\n"
        "          </tbody>\n"
        "        </table>\n"
        "      </div>\n"
        "      {showForm && (\n"
        "        <SupplierFormModal\n"
        "          initial={editing}\n"
        "          onClose={() => { setShowForm(false); setEditing(null); }}\n"
        "          onSave={handleSave}\n"
        "        />\n"
        "      )}\n"
        "    </div>\n"
        "  );\n"
        "}\n"
        "\n"
        "function SupplierFormModal({ initial, onClose, onSave }) {\n"
        "  const [form, setForm] = useState(\n"
        "    initial ? { ...initial } : { name:'', phone:'', email:'', address:'', notes:'' }\n"
        "  );\n"
        "  const [saving, setSaving] = useState(false);\n"
        "  const handleSave = async () => {\n"
        "    if (!form.name.trim()) return;\n"
        "    setSaving(true);\n"
        "    await onSave(form);\n"
        "    setSaving(false);\n"
        "  };\n"
        "  return (\n"
        "    <Modal title={initial ? '\u062a\u0639\u062f\u064a\u0644 \u0645\u0648\u0631\u062f' : '\u0625\u0636\u0627\u0641\u0629 \u0645\u0648\u0631\u062f'} onClose={onClose}>\n"
        "      <div className=\"space-y-3\">\n"
        "        <Field label=\"\u0627\u0644\u0627\u0633\u0645 *\"><input className={INP} value={form.name}\n"
        "          onChange={e=>setForm({...form,name:e.target.value})} /></Field>\n"
        "        <Field label=\"\u0627\u0644\u0647\u0627\u062a\u0641\"><input className={INP} value={form.phone}\n"
        "          onChange={e=>setForm({...form,phone:e.target.value})} /></Field>\n"
        "        <Field label=\"\u0627\u0644\u0628\u0631\u064a\u062f\"><input className={INP} value={form.email}\n"
        "          onChange={e=>setForm({...form,email:e.target.value})} /></Field>\n"
        "        <Field label=\"\u0627\u0644\u0639\u0646\u0648\u0627\u0646\"><textarea className={INP} rows={2} value={form.address}\n"
        "          onChange={e=>setForm({...form,address:e.target.value})} /></Field>\n"
        "        <Field label=\"\u0645\u0644\u0627\u062d\u0638\u0627\u062a\"><textarea className={INP} rows={2} value={form.notes}\n"
        "          onChange={e=>setForm({...form,notes:e.target.value})} /></Field>\n"
        "        <div className=\"flex gap-3 justify-end pt-2\">\n"
        "          <button onClick={onClose} className=\"px-4 py-2 rounded-xl border font-bold text-sm\">\u0625\u0644\u063a\u0627\u0621</button>\n"
        "          <button onClick={handleSave} disabled={saving||!form.name.trim()}\n"
        "            className=\"bg-blue-600 hover:bg-blue-700 text-white font-bold px-5 py-2 rounded-xl text-sm disabled:opacity-50\">\n"
        "            {saving?'...':'\u062d\u0641\u0638'}\n"
        "          </button>\n"
        "        </div>\n"
        "      </div>\n"
        "    </Modal>\n"
        "  );\n"
        "}\n"
    )

    write(path, content)
    print("  OK: PurchasingPage.jsx written from scratch (" + str(len(content)) + " chars)")

# ── Section 4: InventoryPage.jsx — ازالة SuppliersPanel render فقط ────────────
def fix_inventory_page():
    path = FRONTEND + "/pages/InventoryPage.jsx"
    print("\n[InventoryPage.jsx]")

    src = read(path)

    # ازالة تاب الموردين من الـ tabs array لو موجود
    pattern = r",?\s*\{[^}]*key:\s*['\"]suppliers['\"][^}]*\}"
    if re.search(pattern, src):
        backup(path)
        src = re.sub(pattern, "", src, count=1)
        write(path, src)
        print("  OK: removed suppliers tab entry")
    else:
        print("  SKIP: suppliers tab not found in tabs array")

    # ازالة render لـ SuppliersPanel لو موجود
    src = read(path)
    for candidate in [
        "{tab==='suppliers' && <SuppliersPanel />}",
        "{tab === 'suppliers' && <SuppliersPanel />}",
        "tab === 'suppliers' && <SuppliersPanel",
    ]:
        if candidate in src:
            if not src.startswith("# backed up"):
                backup(path)
            src = src.replace(candidate, "", 1)
            write(path, src)
            print("  OK: removed SuppliersPanel render: " + candidate)
            break
    else:
        print("  INFO: SuppliersPanel render not found (may already be removed)")

# ── Section 5: CHANGELOG ──────────────────────────────────────────────────────
def fix_docs():
    print("\n[docs]")
    today = datetime.now().strftime("%Y-%m-%d")
    update_changelog("- " + today + ": Fix-07 purchasing final — all 7 changes applied.")
    print("  OK: CHANGELOG updated")

# ── main ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("fix_07_purchasing_final.py — " + STAMP)
    print("=" * 60)
    if not os.path.isdir(BACKEND):
        abort("BACKEND not found: " + BACKEND)
    if not os.path.isdir(FRONTEND + "/pages"):
        abort("FRONTEND/pages not found")
    fix_models()
    fix_api_js()
    fix_purchasing_page()
    fix_inventory_page()
    fix_docs()
    print("\n" + "=" * 60)
    print("DONE — run migrations:")
    print("  cd " + BASE + "/pos_backend")
    print("  python manage.py makemigrations inventory --name fix07_cleanup")
    print("  python manage.py migrate inventory")
    print("=" * 60)

if __name__ == "__main__":
    main()
