# Generated by Django 4.2.29 on 2026-03-08 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الوحدة')),
                ('symbol', models.CharField(blank=True, default='', max_length=10, verbose_name='الرمز')),
                ('factor', models.DecimalField(decimal_places=4, default=1, help_text='كم وحدة أساسية تعادل هذه الوحدة — مثال: كرتون=12', max_digits=10, verbose_name='معامل التحويل')),
                ('category', models.CharField(choices=[('count', 'عدد'), ('weight', 'وزن'), ('volume', 'حجم'), ('length', 'طول'), ('other', 'أخرى')], default='count', max_length=10)),
                ('is_base', models.BooleanField(default=False, verbose_name='وحدة أساسية')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ['category', 'factor'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع (بالوحدة الأساسية)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشراء (بالوحدة الأساسية)')),
                ('stock', models.IntegerField(default=0, verbose_name='المخزون (بالوحدة الأساسية)')),
                ('min_stock', models.IntegerField(default=10, verbose_name='الحد الأدنى للتنبيه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='products.unitofmeasure', verbose_name='الوحدة الأساسية')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('purchase_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_products', to='products.unitofmeasure', verbose_name='وحدة الشراء الافتراضية')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnitPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_auto', models.BooleanField(default=True, help_text='True = محسوب تلقائياً (base_price × factor) | False = سعر يدوي')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='products.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.unitofmeasure')),
            ],
            options={
                'verbose_name': 'سعر الوحدة',
                'verbose_name_plural': 'أسعار الوحدات',
                'unique_together': {('product', 'unit')},
            },
        ),
    ]
