# Generated by Django 4.2.9 on 2026-03-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='linked_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_alerts', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='ticket_status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('ordered', 'تم الطلب'), ('resolved', 'محلولة')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product'),
        ),
        migrations.CreateModel(
            name='StockAlertNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('note', 'ملاحظة'), ('quote', 'عرض سعر'), ('action', 'إجراء'), ('delay', 'سبب تأخير'), ('system', 'تحديث نظام')], default='note', max_length=10)),
                ('text', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('delay_reason', models.TextField(blank=True, default='')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.stockalert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملاحظة تذكرة',
                'verbose_name_plural': 'ملاحظات التذاكر',
                'ordering': ['created_at'],
            },
        ),
    ]
