# Generated by Django 4.2.9 on 2026-03-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_stockalert_assigned_to_stockalert_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockalert',
            name='linked_po',
        ),
        migrations.AddField(
            model_name='stockalert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='linked_pos',
            field=models.ManyToManyField(blank=True, related_name='linked_alerts', to='inventory.purchaseorder', verbose_name='اوامر الشراء المرتبطة'),
        ),
    ]
