# Generated by Django 4.2.9 on 2026-03-09 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0003_fix07_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stock', models.IntegerField(default=0, verbose_name='المخزون وقت الانشاء')),
                ('threshold', models.IntegerField(default=0, verbose_name='الحد الادنى')),
                ('alert_type', models.CharField(choices=[('low', 'مخزون منخفض'), ('out', 'نفاد المخزون')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_items', to='inventory.stockalert', verbose_name='التنبيه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند تنبيه',
                'verbose_name_plural': 'بنود التنبيهات',
                'unique_together': {('alert', 'product')},
            },
        ),
    ]
