# Generated by Django 4.2.29 on 2026-03-06 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('inventory', '0004_alter_purchaseorderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'عنصر أمر شراء', 'verbose_name_plural': 'عناصر أوامر الشراء'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام المتوقع'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام الفعلي'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المرجع'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('ordered', 'تم الطلب'), ('received', 'تم الاستلام'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي التكلفة'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية المطلوبة'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسوية'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_after',
            field=models.IntegerField(verbose_name='الكمية بعد'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_before',
            field=models.IntegerField(verbose_name='الكمية قبل'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(verbose_name='التغيير'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('count', 'جرد دوري'), ('damage', 'تلف'), ('loss', 'فقد / سرقة'), ('return', 'مرتجع من عميل'), ('expiry', 'انتهاء صلاحية'), ('other', 'أخرى')], default='count', max_length=20, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('low', 'مخزون منخفض'), ('out', 'نفاد المخزون'), ('expiry', 'قرب انتهاء الصلاحية')], max_length=20, verbose_name='نوع التنبيه'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنبيه'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='current_stock',
            field=models.IntegerField(verbose_name='المخزون الحالي وقت التنبيه'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='تم الحل'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='threshold',
            field=models.IntegerField(default=10, verbose_name='حد التنبيه'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
