# Generated by Django 4.2.29 on 2026-03-08 15:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='رصيد الافتتاح')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('opening_note', models.TextField(blank=True, default='', verbose_name='ملاحظة الافتتاح')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رصيد الإغلاق')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('closing_note', models.TextField(blank=True, default='', verbose_name='ملاحظة الإغلاق')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي مبيعات النقد')),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي مبيعات البطاقة')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المبيعات')),
                ('total_returns', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المرتجعات')),
                ('total_cash_returns', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المرتجعات النقدية')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='النقد المتوقع')),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='النقد الفعلي')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الفرق')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق')], default='open', max_length=10, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل الخزنة',
                'verbose_name_plural': 'سجلات الخزنة',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.cashregister')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('both', 'نقدي + بطاقة')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('pending', 'قيد الانتظار')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.cashregister')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'عمليات البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='الكمية بوحدة البيع')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unitofmeasure', verbose_name='وحدة البيع')),
            ],
            options={
                'verbose_name': 'عنصر بيع',
                'verbose_name_plural': 'عناصر البيع',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'عنصر مرتجع',
                'verbose_name_plural': 'عناصر المرتجعات',
            },
        ),
        migrations.AddField(
            model_name='return',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='return',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('adjustment', 'تسوية'), ('return', 'مرتجع')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحركة')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.cashregister', verbose_name='سجل الخزنة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'حركة خزنة',
                'verbose_name_plural': 'حركات الخزنة',
                'ordering': ['-created_at'],
            },
        ),
    ]
