# Generated by Django 4.2.29 on 2026-03-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_invoice_number_sale_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paid_amount',
        ),
    ]
