# Generated by Django 4.2.29 on 2026-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_invoice_number_remove_sale_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المدفوع'),
        ),
    ]
