# Generated by Django 4.2.29 on 2026-03-07 17:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_sale_invoice_number_sale_paid_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-opened_at'], 'verbose_name': 'سجل الخزنة', 'verbose_name_plural': 'سجلات الخزنة'},
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'حركة خزنة', 'verbose_name_plural': 'حركات الخزنة'},
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='النقد الفعلي'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='cash_difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الفرق'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رصيد الإغلاق'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closing_note',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظة الإغلاق'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='النقد المتوقع'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='رصيد الافتتاح'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_note',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظة الافتتاح'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_card_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي مبيعات البطاقة'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_cash_returns',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المرتجعات النقدية'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_cash_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي مبيعات النقد'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_returns',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المرتجعات'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المبيعات'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.cashregister', verbose_name='سجل الخزنة'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الحركة'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('adjustment', 'تسوية'), ('return', 'مرتجع')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
