# Generated by Django 4.2.29 on 2026-03-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0006_alter_cashregister_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
    ]
